
// SET firebase config stuffs

firebase functions:config:get > .runtimeconfig.json
firebase functions:config:set someservice.key="THE API KEY"
firebase functions:config:set database.dev.password=""

// https://firebase.google.com/docs/functions/config-env


export GOOGLE_APPLICATION_CREDENTIALS="/Users/xfhg/Code/production/xpert/xpert.id/functions/nlpapi-xpert-id-c20ed255e9b4.json"
gcloud ml language analyze-entities --content="Michelangelo Caravaggio, Italian painter, is known for 'The Calling of Saint Matthew'."
